# frontend/cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/frontend-app',
      '--build-arg', 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}', '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/frontend-app'
