# backend/cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/backend-app',
      --set-env-vars GOOGLE_API_KEY=$GOOGLE_API_KEY,FRONTEND_URL=$FRONTEND_URL \
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/backend-app'
